// Shared pixel UI kit helpers, imported from StarScape. The atlas is a free-rect sheet
// loaded under the 'ui' texture key; 9-slice frames carry a `border` inset that must not
// stretch. These wrap Phaser's NineSlice/Image so any scene can draw a panel, dialogue
// box, button, or bar without knowing the frame geometry.
//
// Changed on import: the atlas is generated by src/uiatlas.js rather than loaded from a
// painted ui.png, the palette below reads COLORS.ui in tuning.js instead of carrying its
// own hex values, and the activity frame measures itself against TUNING.viewWidth /
// viewHeight. Nothing else moved, so a StarScape engine drops in against this unchanged.
import { TUNING, COLORS, hex } from '../../tuning.js';
import { ART } from '../uiatlas.js';

const FRAME = {};
for (const f of ART.ui.frames) FRAME[f.name] = f;

export function uiFrame(name) {
  return FRAME[name];
}

// A 9-slice panel at (x,y) with the given size. `name` picks the frame (panel,
// panel_inset, hud_plate, dialogue_box, btn, track, …). Falls back to a plain
// stretched image for non-bordered frames. Returns the game object (origin 0.5).
export function panel(scene, x, y, w, h, name = 'panel') {
  const f = FRAME[name];
  if (!f) throw new Error(`ui frame "${name}" not found`);
  if (f.border) {
    const b = f.border;
    return scene.add.nineslice(x, y, 'ui', name, w, h, b.left, b.right, b.top, b.bottom);
  }
  return scene.add.image(x, y, 'ui', name).setDisplaySize(w, h);
}

// Palette tokens. Every value comes from COLORS.ui in tuning.js, so retinting the kit is
// an edit to that block and nothing here.
export const COLOR = {
  stage: COLORS.ui.stage,
  text: hex(COLORS.ui.text),
  muted: hex(COLORS.ui.muted),
  gold: hex(COLORS.ui.gold),
  goldBright: hex(COLORS.ui.goldBright),
  grass: hex(COLORS.ui.grass),
  danger: hex(COLORS.ui.danger),
  cool: hex(COLORS.ui.cool),
  warn: hex(COLORS.ui.warn),
  onWood: hex(COLORS.ui.text),
  ink: hex(COLORS.ui.ink),
};

// The face, taken off tuning.js the same way the palette is, so an engine that reads its
// colours from the kit reads its lettering from it too.
export const FONT = TUNING.font;

// Paint a scene's background the stage colour — call once in create().
export function stage(scene) {
  scene.cameras.main.setBackgroundColor(COLOR.stage);
}

// A screen title (top-left by default). A light fill and a dark stroke keeps it legible
// on both the dark stage and a lighter scrim.
export function title(scene, text, x = 32, y = 26) {
  const t = scene.add.text(x, y, text, { fontFamily: FONT, fontSize: '26px', color: COLOR.onWood });
  t.setStroke(COLOR.ink, 4);
  return t;
}

// A 9-slice button with a centered label and hover/press feedback. `locked` uses
// the hatched frame and drops the click handler. Returns { bg, label }.
export function button(scene, cx, cy, w, h, label, onClick, opts = {}) {
  const frame = opts.locked ? 'btn_locked' : 'btn';
  const bg = panel(scene, cx, cy, w, h, frame);
  const color = opts.locked ? COLOR.muted : opts.color ?? COLOR.text;
  const style = { fontFamily: FONT, fontSize: opts.fontSize ?? '17px', color };
  const txt = opts.align === 'left'
    ? scene.add.text(cx - w / 2 + 14, cy, label, style).setOrigin(0, 0.5)
    : scene.add.text(cx, cy, label, style).setOrigin(0.5);
  if (!opts.locked && onClick) {
    // resting → lifted → sunk. All btn* frames share the geometry and insets, so
    // swapping the frame under the label is safe.
    bg.setInteractive({ useHandCursor: true })
      .on('pointerover', () => bg.setFrame('btn_hover'))
      .on('pointerout', () => bg.setFrame('btn'))
      .on('pointerdown', () => { bg.setFrame('btn_pressed'); onClick(); })
      .on('pointerup', () => bg.setFrame('btn_hover'));
  }
  return { bg, label: txt };
}

// A back button (top-left). Returns the button parts.
export function backButton(scene, onClick, cx = 84, cy = 44) {
  return button(scene, cx, cy, 104, 30, '‹ Back', onClick, { fontSize: '16px' });
}

// A feedback ribbon (PERFECT/CLEAN/GOOD/MISS/WILD): the colored fb_* container with
// the label rendered on top. Returns a container.
export function feedback(scene, cx, cy, kind) {
  const name = `fb_${kind.toLowerCase()}`;
  const ribbon = scene.add.image(0, 0, 'ui', FRAME[name] ? name : 'fb_good');
  const txt = scene.add.text(0, -1, kind.toUpperCase(), { fontFamily: FONT, fontSize: '13px', color: COLOR.ink }).setOrigin(0.5);
  return scene.add.container(cx, cy, [ribbon, txt]);
}

// An inventory slot frame (slot / slot_equipped / slot_empty). Returns the image.
export function slot(scene, cx, cy, size = 34, kind = 'slot') {
  return panel(scene, cx, cy, size, size, kind);
}

// A simple horizontal bar built from a *_track + *_fill pair. Returns
// { container, setValue(pct) } — setValue clips the fill width to 0..1.
export function bar(scene, x, y, w, h, kind = 'bar_hp') {
  const track = panel(scene, x, y, w, h, `${kind}_track`).setOrigin(0, 0.5);
  const f = FRAME[`${kind}_fill`];
  const inset = FRAME[`${kind}_track`]?.border?.left ?? 2;
  const fill = scene.add.image(x + inset, y, 'ui', `${kind}_fill`).setOrigin(0, 0.5);
  const usable = w - inset * 2;
  const setValue = (pct) => {
    const p = Math.max(0, Math.min(1, pct));
    fill.setDisplaySize(usable * p, h - inset * 2);
    fill.setCrop(0, 0, f.w * p, f.h);
    fill.setVisible(p > 0);
  };
  setValue(1);
  return { track, fill, setValue };
}

// Shared inset for corner/edge modal elements, and an explicit depth order so activity-scene
// chrome never overlaps by accident. The diorama/backdrop live below `panel`; text above it;
// interactive controls on top. Scenes and the ActivityStage both read these.
export const INSET = 22;
export const DEPTH = { backdrop: -1000, diorama: -40, panel: 800, text: 900, control: 950 };

// One layout system for an activity scene's chrome — a header (title + Back), a description
// strip, a status footer (message + optional action button), and a computed **body rect** the
// scene fills (a recipe list, a requirements panel, or the live diorama). Everything stacks at
// consistent insets and explicit depths, so nothing hardcodes offsets or overlaps. Returns
// handles to update each region.
export function activityFrame(scene, { title: titleStr = '', onBack, backLabel = '‹ Back' } = {}) {
  const W = TUNING.viewWidth, H = TUNING.viewHeight, innerW = W - INSET * 2;
  const bar = (cy, h) => panel(scene, W / 2, cy, innerW, h, 'panel').setDepth(DEPTH.panel);

  const headerH = 50, headerCy = INSET + headerH / 2;
  const header = bar(headerCy, headerH);
  const titleText = scene.add
    .text(INSET + 16, headerCy, titleStr, { fontFamily: FONT, fontSize: '20px', color: COLOR.gold })
    .setOrigin(0, 0.5).setDepth(DEPTH.text);
  let back = null;
  if (onBack) {
    back = button(scene, W - INSET - 58, headerCy, 100, 32, backLabel, onBack, { fontSize: '14px' });
    back.bg.setDepth(DEPTH.control); back.label.setDepth(DEPTH.control);
  }

  const descH = 56, descCy = INSET + headerH + 8 + descH / 2;
  const descBar = bar(descCy, descH);
  const descText = scene.add
    .text(INSET + 16, descCy, '', { fontFamily: FONT, fontSize: '15px', color: COLOR.muted, wordWrap: { width: innerW - 32 }, lineSpacing: 3 })
    .setOrigin(0, 0.5).setDepth(DEPTH.text);

  const footerH = 54, footerCy = H - INSET - footerH / 2;
  const footer = bar(footerCy, footerH);
  const statusText = scene.add
    .text(INSET + 16, footerCy, '', { fontFamily: FONT, fontSize: '16px', color: COLOR.text, wordWrap: { width: innerW - 220 }, lineSpacing: 2 })
    .setOrigin(0, 0.5).setDepth(DEPTH.text);
  let action = null;

  const bodyTop = descCy + descH / 2 + 10;
  const bodyBottom = footerCy - footerH / 2 - 10;
  const body = { x: INSET, y: bodyTop, w: innerW, h: bodyBottom - bodyTop, cx: W / 2, cy: (bodyTop + bodyBottom) / 2 };

  const owned = [header, descBar, footer, titleText, descText, statusText, ...(back ? [back.bg, back.label] : [])];
  return {
    body,
    setTitle: (s) => titleText.setText(s),
    setDescription: (s) => descText.setText(s ?? ''),
    setStatus: (s, color) => { statusText.setText(s ?? ''); statusText.setColor(color ?? COLOR.text); },
    // A right-aligned footer button (Try Again / Forge Again / …). Pass null to clear it.
    setAction: (label, onClick, color) => {
      action?.bg.destroy(); action?.label.destroy(); action = null;
      if (!label) return;
      action = button(scene, W - INSET - 92, footerCy, 168, 36, label, onClick, { color });
      action.bg.setDepth(DEPTH.control); action.label.setDepth(DEPTH.control);
    },
    destroy: () => { owned.forEach((o) => o.destroy()); action?.bg.destroy(); action?.label.destroy(); },
  };
}

// A plain text result card filling the frame body (a craft outcome, a catch summary, a crack
// notice). One opaque plate + wrapped text at the shared depths so any activity scene shows its
// result the same way. Returns { objects, destroy } — the caller pushes objects into its own
// teardown list. `color` tints the text (danger red on a failure).
export function resultCard(scene, body, text, color = COLOR.text) {
  const w = Math.min(620, body.w - 30), h = Math.min(300, body.h - 16);
  const cy = body.y + h / 2 + 6;
  const p = panel(scene, body.cx, cy, w, h, 'panel').setDepth(DEPTH.panel + 5);
  const t = scene.add
    .text(body.cx - w / 2 + 26, cy - h / 2 + 24, text, { fontFamily: FONT, fontSize: '16px', color, wordWrap: { width: w - 52 }, lineSpacing: 7 })
    .setOrigin(0, 0).setDepth(DEPTH.text);
  return { objects: [p, t], destroy: () => { p.destroy(); t.destroy(); } };
}

// A recipe requirements card for the frame body: the inputs (with have/need counts, shortfalls
// in red) and the output line. Data-driven from a plain spec so any craft scene can render it.
// spec: { output, outputNote?, inputs: [{ label, need, have }], footnote? }. Returns { destroy }.
export function recipeCard(scene, bodyRect, spec) {
  const owned = [];
  const cardW = Math.min(560, bodyRect.w - 40);
  const cardH = Math.min(300, bodyRect.h - 20);
  const cx = bodyRect.cx, cy = bodyRect.y + cardH / 2 + 8;
  const leftX = cx - cardW / 2 + 26;
  const rightX = cx + cardW / 2 - 26;
  owned.push(panel(scene, cx, cy, cardW, cardH, 'panel').setDepth(DEPTH.panel + 5));
  let y = cy - cardH / 2 + 22;
  const line = (t, style, x = leftX, origin = 0) => {
    const o = scene.add.text(x, y, t, { fontFamily: FONT, ...style }).setOrigin(origin, 0).setDepth(DEPTH.text);
    owned.push(o);
    return o;
  };

  line('Requires', { fontSize: '15px', color: COLOR.gold });
  y += 28;
  for (const inp of spec.inputs) {
    const short = inp.have < inp.need;
    line(`•  ${inp.label} ×${inp.need}`, { fontSize: '16px', color: COLOR.text });
    line(`have ${inp.have}`, { fontSize: '15px', color: short ? COLOR.danger : COLOR.grass }, rightX, 1);
    y += 26;
  }
  y += 10;
  line('Produces', { fontSize: '15px', color: COLOR.gold });
  y += 26;
  line(`•  ${spec.output}`, { fontSize: '16px', color: COLOR.text });
  if (spec.outputNote) { y += 24; line(spec.outputNote, { fontSize: '14px', color: COLOR.muted, wordWrap: { width: cardW - 52 } }); }
  if (spec.footnote) { y += 30; line(spec.footnote, { fontSize: '13px', color: COLOR.muted, wordWrap: { width: cardW - 52 } }); }
  return { destroy: () => owned.forEach((o) => o.destroy()) };
}
