// Maps are character grids. Editing the world means typing over characters.
// Every row of a map must be the same length and every character must be in LEGEND.

// solid: blocks movement. above: a second tile drawn over actors standing here.
export const TILES = {
  grass: {},
  path: {},
  dirt: {},
  wood: {},
  stone: {},
  rug: {},
  door: {},
  water: { solid: true },
  tree: { solid: true, above: 'treetop' },
  wall: { solid: true },
  roof: { solid: true },
  well: { solid: true },
  grave: { solid: true },
  bar: { solid: true },
  forge: { solid: true },
  shelf: { solid: true },
  altar: { solid: true },
  pew: { solid: true },
  crate: { solid: true },
  hearth: { solid: true },
  bed: {}, // you can lie on it
  sand: {},
  flotsam: {}, // small wreckage; you walk over it
  spar: { solid: true }, // ship timber; you walk around it
};

export const LEGEND = {
  '.': 'grass',
  ',': 'path',
  ':': 'dirt',
  '~': 'water',
  T: 'tree',
  '#': 'wall',
  '=': 'roof',
  D: 'door',
  _: 'wood',
  '+': 'stone',
  o: 'well',
  x: 'grave',
  b: 'bar',
  f: 'forge',
  s: 'shelf',
  a: 'altar',
  p: 'pew',
  c: 'crate',
  h: 'hearth',
  r: 'rug',
  B: 'bed',
  S: 'sand',
  w: 'flotsam',
  W: 'spar',
};

export const MAPS = {
  // Where the player wakes up the morning after. Aldis carried them here.
  hut: {
    name: 'Aldis Rooke\'s house',
    spawn: [8, 10],
    rows: [
      '##################',
      '#hh______________#',
      '#hh______________#',
      '#________________#',
      '#BBB_____cc______#',
      '#________cc______#',
      '#________________#',
      '#___ss___________#',
      '#______rrrr______#',
      '#______rrrr______#',
      '#________________#',
      '########D#########',
    ],
    doors: [{ x: 8, y: 11, to: 'village', spawn: [16, 16] }],
  },

  // Where the game opens, and the western edge of the town afterwards. The tide put the
  // player here and the storm put everything else; the village lane runs out onto it.
  shore: {
    name: 'The Dreadhollow outskirts',
    spawn: [16, 8],
    rows: [
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      'SS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~SS',
      'SSSSS~~~~~~~~~~~~~~~~~~~~~~~~SSSSS',
      'SSSSSSSSwSSS~~~~~~~~~~~SSSSSSSSSSS',
      'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
      'SSSwSSSSSSSSSSSSSSSSSSWSSSwSSSSSSS',
      'SSSSSSSSSSWSSSSSSSSSSSSSSSSSSSSSSS',
      'SSSSwSSSSSSSSSSSwSSSSSSSSSSSWSSSSS',
      'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
      '..SSSSSS..SSSS....SSSS..SSSSSS....',
      '.................,................',
      'TTTTTTTTTTTTTTTTT,TTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTTT,TTTTTTTTTTTTTTTT',
    ],
    doors: [{ x: 17, y: 15, to: 'village', spawn: [3, 21] }],
  },
  village: {
    name: 'Dreadhollow',
    spawn: [19, 12],
    rows: [
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'TT.................,,.................TT',
      'TT...T.............,,............T....TT',
      'TT..=======........,,.......=======...TT',
      'TT..=======........,,.......=======...TT',
      'TT..#######........,,.......#######...TT',
      'TT..###D###........,,.......#######...TT',
      'TT.....,...........,,..........,......TT',
      'TT.....,...........,,..........,......TT',
      'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
      'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
      'TT...........,=====,,....,............TT',
      'TT...........,=====,,.oo.,............TT',
      'TT...........,#####,,.oo.,............TT',
      'TT...........,##D##,,....,..======....TT',
      'TT..=======..,.....,,....,..======....TT',
      'TT..=======..,.....,,....,..######....TT',
      'TT..#######..,.....,,....,..######....TT',
      'TT..###D###..,.....,,....,..######....TT',
      'TT.....,.....,.....,,....,....,.......TT',
      'T,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
      'TT.................,,.................TT',
      'TT.~~~~~~~~~.......,,....x.x.x.x.x....TT',
      'TT.~~~~~~~~~.......,,.................TT',
      'TT.~~~~~~~~~.......,,....x.x.x.x.x....TT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    doors: [
      { x: 7, y: 7, to: 'tavern', spawn: [9, 13] },
      { x: 2, y: 21, to: 'shore', spawn: [17, 14] },
      { x: 16, y: 15, to: 'hut', spawn: [8, 10] },
    ],
  },

  tavern: {
    name: 'The Sea Hag',
    spawn: [9, 13],
    rows: [
      '######################',
      '#hh__________________#',
      '#hh__________________#',
      '#____________________#',
      '#__bbbbbbbb__________#',
      '#__bbbbbbbb__________#',
      '#____________________#',
      '#___cc_____cc____cc__#',
      '#____________________#',
      '#___cc_____cc____cc__#',
      '#____________________#',
      '#_____rrrrrrrr_______#',
      '#_____rrrrrrrr_______#',
      '#____________________#',
      '#########D############',
    ],
    doors: [{ x: 9, y: 14, to: 'village', spawn: [7, 8] }],
  },



};
