// Maps are character grids. Editing the world means typing over characters.
// Every row of a map must be the same length and every character must be in LEGEND.

// solid: blocks movement. above: a second tile drawn over actors standing here.
export const TILES = {
  grass: {},
  path: {},
  dirt: {},
  wood: {},
  stone: {},
  rug: {},
  door: {},
  water: { solid: true },
  tree: { solid: true, above: 'treetop' },
  wall: { solid: true },
  roof: { solid: true },
  well: { solid: true },
  grave: { solid: true },
  bar: { solid: true },
  forge: { solid: true },
  shelf: { solid: true },
  altar: { solid: true },
  pew: { solid: true },
  crate: { solid: true },
  hearth: { solid: true },
  sand: {},
  flotsam: {}, // small wreckage; you walk over it
  spar: { solid: true }, // ship timber; you walk around it
};

export const LEGEND = {
  '.': 'grass',
  ',': 'path',
  ':': 'dirt',
  '~': 'water',
  T: 'tree',
  '#': 'wall',
  '=': 'roof',
  D: 'door',
  _: 'wood',
  '+': 'stone',
  o: 'well',
  x: 'grave',
  b: 'bar',
  f: 'forge',
  s: 'shelf',
  a: 'altar',
  p: 'pew',
  c: 'crate',
  h: 'hearth',
  r: 'rug',
  S: 'sand',
  w: 'flotsam',
  W: 'spar',
};

export const MAPS = {
  // Where the game opens. The tide put the player here and the storm put everything
  // else. Reachable afterwards from the west end of the village lane.
  shore: {
    name: 'The strand',
    spawn: [16, 8],
    rows: [
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      'SS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~SS',
      'SSSSS~~~~~~~~~~~~~~~~~~~~~~~~SSSSS',
      'SSSSSSSSwSSS~~~~~~~~~~~SSSSSSSSSSS',
      'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
      'SSSwSSSSSSSSSSSSSSSSSSWSSSwSSSSSSS',
      'SSSSSSSSSSWSSSSSSSSSSSSSSSSSSSSSSS',
      'SSSSwSSSSSSSSSSSwSSSSSSSSSSSWSSSSS',
      'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
      '..SSSSSS..SSSS....SSSS..SSSSSS....',
      '.................,................',
      'TTTTTTTTTTTTTTTTT,TTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTTT,TTTTTTTTTTTTTTTT',
    ],
    doors: [{ x: 17, y: 15, to: 'village', spawn: [3, 21] }],
  },
  village: {
    name: 'Dreadhollow',
    spawn: [19, 12],
    rows: [
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'TT.................,,.................TT',
      'TT...T.............,,............T....TT',
      'TT..=======........,,.......=======...TT',
      'TT..=======........,,.......=======...TT',
      'TT..#######........,,.......#######...TT',
      'TT..###D###........,,.......###D###...TT',
      'TT.....,...........,,..........,......TT',
      'TT.....,...........,,..........,......TT',
      'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
      'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
      'TT...........,.....,,....,............TT',
      'TT...........,.....,,.oo.,............TT',
      'TT...........,.....,,.oo.,............TT',
      'TT...........,.....,,....,.========...TT',
      'TT..=======..,.....,,....,.========...TT',
      'TT..=======..,.....,,....,.########...TT',
      'TT..#######..,.....,,....,.########...TT',
      'TT..###D###..,.....,,....,.###D####...TT',
      'TT.....,.....,.....,,....,....,.......TT',
      'T,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
      'TT.................,,.................TT',
      'TT.~~~~~~~~~.......,,....x.x.x.x.x....TT',
      'TT.~~~~~~~~~.......,,.................TT',
      'TT.~~~~~~~~~.......,,....x.x.x.x.x....TT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    doors: [
      { x: 7, y: 7, to: 'tavern', spawn: [9, 13] },
      { x: 31, y: 7, to: 'smithy', spawn: [9, 13] },
      { x: 7, y: 19, to: 'apothecary', spawn: [9, 13] },
      { x: 30, y: 19, to: 'chapel', spawn: [9, 13] },
      { x: 2, y: 21, to: 'shore', spawn: [17, 14] },
    ],
  },

  tavern: {
    name: 'The Sea Hag',
    spawn: [9, 13],
    rows: [
      '######################',
      '#hh__________________#',
      '#hh__________________#',
      '#____________________#',
      '#__bbbbbbbb__________#',
      '#__bbbbbbbb__________#',
      '#____________________#',
      '#___cc_____cc____cc__#',
      '#____________________#',
      '#___cc_____cc____cc__#',
      '#____________________#',
      '#_____rrrrrrrr_______#',
      '#_____rrrrrrrr_______#',
      '#____________________#',
      '#########D############',
    ],
    doors: [{ x: 9, y: 14, to: 'village', spawn: [7, 8] }],
  },

  smithy: {
    name: "Krael's Forge",
    spawn: [9, 13],
    rows: [
      '######################',
      '#____________________#',
      '#__ffff______________#',
      '#__ffff______________#',
      '#____________________#',
      '#___cc_______cc______#',
      '#____________________#',
      '#________ssss________#',
      '#____________________#',
      '#___cc_______cc______#',
      '#____________________#',
      '#____________________#',
      '#____________________#',
      '#____________________#',
      '#########D############',
    ],
    doors: [{ x: 9, y: 14, to: 'village', spawn: [31, 8] }],
  },

  apothecary: {
    name: 'The Green Room',
    spawn: [9, 13],
    rows: [
      '######################',
      '#ssssss______________#',
      '#____________________#',
      '#___ss_______ss______#',
      '#____________________#',
      '#____________________#',
      '#______bbbbbb________#',
      '#______bbbbbb________#',
      '#____________________#',
      '#___cc_________cc____#',
      '#____________________#',
      '#____________________#',
      '#____________________#',
      '#____________________#',
      '#########D############',
    ],
    doors: [{ x: 9, y: 14, to: 'village', spawn: [7, 20] }],
  },

  chapel: {
    name: 'Chapel of the Quiet Hour',
    spawn: [9, 13],
    rows: [
      '######################',
      '#++++++aaaaaa++++++++#',
      '#++++++++++++++++++++#',
      '#++++++++++++++++++++#',
      '#__pppppp__pppppp____#',
      '#++++++++++++++++++++#',
      '#__pppppp__pppppp____#',
      '#++++++++++++++++++++#',
      '#__pppppp__pppppp____#',
      '#++++++++++++++++++++#',
      '#__pppppp__pppppp____#',
      '#++++++++++++++++++++#',
      '#++++++++++++++++++++#',
      '#++++++++++++++++++++#',
      '#########D############',
    ],
    doors: [{ x: 9, y: 14, to: 'village', spawn: [30, 20] }],
  },
};
